# Generated by Django 5.2 on 2025-05-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_presence_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='eleves_photos/'),
        ),
    ]
