# Generated by Django 5.2 on 2025-05-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_eleve_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='photo',
        ),
        migrations.AddField(
            model_name='eleve',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='eleves/'),
        ),
    ]
